[phases.setup]
nixPkgs = ["php", "composer", "php-extensions.mysql", "php-extensions.pdo"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = ["php artisan config:cache", "php artisan route:cache", "php artisan view:cache"]

[start]
cmd = "bash start.sh" 